#!/bin/bash

# Script to copy all HTML files from results/ to _site/

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

# Create _site directory if it doesn't exist
mkdir -p "$PROJECT_ROOT/_site"

# Copy all HTML files
echo "Copying HTML files to _site directory..."

cp "$PROJECT_ROOT/results/organization_report.html" "$PROJECT_ROOT/_site/" 2>/dev/null && echo "✓ Copied organization_report.html" || echo "⚠ organization_report.html not found"

cp "$PROJECT_ROOT/results/metadata_viewer.html" "$PROJECT_ROOT/_site/" 2>/dev/null && echo "✓ Copied metadata_viewer.html" || echo "⚠ metadata_viewer.html not found"

cp "$PROJECT_ROOT/results/correction_interface.html" "$PROJECT_ROOT/_site/" 2>/dev/null && echo "✓ Copied correction_interface.html" || echo "⚠ correction_interface.html not found"

cp "$PROJECT_ROOT/results/ml_data_explorer.html" "$PROJECT_ROOT/_site/" 2>/dev/null && echo "✓ Copied ml_data_explorer.html" || echo "⚠ ml_data_explorer.html not found"

# _site/index.html is the committed dashboard source — results/index.html is
# a stale scratch copy (regenerated by update-site). Copying it here would
# silently overwrite the maintained version. Skip it; run update-site (or
# organize-files update-site) to regenerate _site/index.html properly.
echo "⚠ Skipping results/index.html — _site/index.html is the maintained source"

# Copy cost report for dynamic data loading
if [ -f "$PROJECT_ROOT/results/cost_report.json" ]; then
    cp "$PROJECT_ROOT/results/cost_report.json" "$PROJECT_ROOT/_site/"
    echo "✓ Copied cost_report.json"
fi

echo ""
echo "All files copied successfully to _site directory!"
echo ""
echo "Files in _site:"
ls -lh "$PROJECT_ROOT/_site/"
